In [ ]:
#4. Given the dictionary {“name”:”angela”, “surname":”lee”}, how do you extract the value of the surname (i.e. “lee”)?

a = {'name': 'angela', 'surname':'lee'}

a.get('surname')

a.keys()[a.values().index('lee')] # Prints Surname / Reverse lookup



In [ ]:
pokedex = {
    1:{'name':'charmander',
        'type': 'fire',
        'hp': 100,
        'attack': 100,
        'defense': 100,
        'special_attack': 100,
        'special_defense': 100,
        'speed': 100
      },
    2:{'name':'squirtle',
        'type': 'water',
        'hp': 99,
        'attack': 99,
        'defense': 99,
        'special_attack': 99,
        'special_defense': 99,
        'speed': 99
      },
    3:{'name':'bulbasaur',
        'type': 'poison',
        'hp': 97,
        'attack': 97,
        'defense': 97,
        'special_attack': 97,
        'special_defense': 97,
        'speed': 97
      }
        
    
}

In [ ]:
pokedex[[n[0] for n in pokedex.items() if n[1]['name'] == 'charmander'][0]]

In [ ]:
count1 = 0
count2 = 0

print(len(pokemon_gyms))

for n in pokemon_gyms:
    count1 += 1
    for k, v in players.items():
        count2 += 1
        if n in v.gyms_visited:
            pprint('{0}, has visited {1}'.format(v.player_name, n))
            
print('Count 1: '+str(count1))
print('Count 2: '+str(count2))


In [15]:
a = ['"001","Bulbasaur","GrassPoison","318","45","49","49","65","65","45"']

[m.replace('"','') for m in a[0].split(",")]

['001', 'Bulbasaur', 'GrassPoison', '318', '45', '49', '49', '65', '65', '45']

In [17]:
#[float(n) for n in [m.replace('"','') for m in a.split(",")] if n.isnumeric()]

[float(n) for n in [m.replace('"','') for m in a[0].split(",")] if n.isdigit()]

[1.0, 318.0, 45.0, 49.0, 49.0, 65.0, 65.0, 45.0]

In [ ]:
a ='123123'
a.isdigit()

In [18]:
strings = [ ['foo', 'bar'], ['baz', 'taz'], ['w', 'koko'] ]
[ (letter, idx) for idx, lst in enumerate(strings) for word in lst if len(word)>2 for letter in word]


[('f', 0),
 ('o', 0),
 ('o', 0),
 ('b', 0),
 ('a', 0),
 ('r', 0),
 ('b', 1),
 ('a', 1),
 ('z', 1),
 ('t', 1),
 ('a', 1),
 ('z', 1),
 ('k', 2),
 ('o', 2),
 ('k', 2),
 ('o', 2)]

In [ ]:
#### TRADITIONAL ####
#pokedex = []
#templist = []
#for line in raw_pd.splitlines():
#    itemlist = line.split(",")
#    for items in itemlist:
#        if items.isdigit():
#            templist.append(float(items))
#        else:
#            templist.append(items)
#    pokedex.append(templist)


#print(pokedex)

#[[line][0].split(',') for line in raw_pd.splitlines()]

#[n.replace('"','') for row in [[line][0].split(',') for line in raw_pd.splitlines()] for n in row]

[[line][0].split(',') for line in raw_pd.split('\n')]

headers = df.columns.tolist()

body= df.values.tolist()

pokedex = [headers]+body

pprint(pokedex)


[[l if not l.isdigit() else float(l) for l in k] for k in [[j.strip("'") for j in i] for i in [[line][0].split(',') for line in raw_pd.replace('"',"'").split('\n')]]]

In [5]:
import numpy as np

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(a)

'''array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])'''

print(a[np.triu_indices(3)])
#or
print(list(a[np.triu_indices(3)]))

print(a[np.triu_indices(3, k = 1)])



[[1 2 3]
 [4 5 6]
 [7 8 9]]
[1 2 3 5 6 9]
[1, 2, 3, 5, 6, 9]
[2 3 6]


In [8]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a
'''array([[1, 2, 3],
           [4, 5, 6],
           [7, 8, 9]])
tri_upper_diag = np.triu(a, k=0)
tri_upper_diag
   array([[1, 2, 3],
           [0, 5, 6],
           [0, 0, 9]])

tri_upper_no_diag = np.triu(a, k=1)
tri_upper_no_diag
    array([[0, 2, 3],
           [0, 0, 6],
           [0, 0, 0]])

tri_lower_diag = np.tril(a, k=0)
tri_lower_diag
    array([[1, 0, 0],
           [4, 5, 0],
           [7, 8, 9]])

tri_lower_no_diag = np.tril(a, k=-1)
tri_lower_no_diag
array([[0, 0, 0],
           [4, 0, 0],
           [7, 8, 0]])'''

a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

tri_upper_diag = np.triu(a, k=0)
tri_upper_diag


tri_upper_no_diag = np.triu(a, k=1)
tri_upper_no_diag


tri_lower_diag = np.tril(a, k=0)
tri_lower_diag


tri_lower_no_diag = np.tril(a, k=-1)
tri_lower_no_diag



array([[0, 0, 0],
       [4, 0, 0],
       [7, 8, 0]])

In [ ]:
>>> s = 'sdsd'
>>> s.upper()
'SDSD'

def listfixer(tofix):
    
    reverse_list = tofix[::-1]
    
    odd_list = tofix[1::2]
    
    return(reverse_list, odd_list)
    
    '''tofix2 = list(tofix)
    fixed_rev = tofix
    fixed_rev.reverse()
    fixed_odd = [i for i in tofix2 if tofix2.index(i) % 2 != 0]
    return (fixed_rev, fixed_odd)'''

print(range(10))
listfixer(range(10))

Skewness and measures of central tendency
The mean, median, and mode are affected by skewness.

When a distribution is symmetric, the mean, median, and mode are the same.

Symmetric: mean == median == mode

When a distribution is negatively skewed, the mean is less than the median, which is less than the mode.

Negative skew: mean < median < mode

When a distribution is positively skewed, the mean is greater than the median, which is greater than the mode.

Positive skew: mode < median < mean

In [ ]:
print('Mean: {0}   Median: {1}   Mode: {2}'.format(np.mean(dist), np.median(dist), mode(rounded)[0][0]))

if np.mean(dist) < np.median(dist) < mode(rounded)[0][0]:
    print('Negative Skew')
elif mode(rounded)[0][0] < np.median(dist) < np.mean(dist):
    print('Positive Skew')


In [ ]:
def getUniqueWords(allWords) :
    uniqueWords = [] 
    for i in allWords:
        if not i in uniqueWords:
            uniqueWords.append(i)
    return uniqueWords

print getUniqueWords(['a','b','c','a','b']);

In [ ]:
import csv
print 'Opening File. Data: '
csv_rows = []
with open('./datasets/sales_info.csv', 'rU') as f:
    reader = csv.reader(f)
    for row in reader:
        csv_rows.append(row)
f.close()
print 'file closed'   # Always remember to close the file after writing to it!

https://stats.stackexchange.com/questions/70801/how-to-normalize-data-to-0-1-range


In [ ]:
def get_redundant_pairs(df):
    '''Get diagonal and lower triangular pairs of correlation matrix'''
    pairs_to_drop = set()
    cols = df.columns
    for i in range(0, df.shape[1]):
        for j in range(0, i+1):
            pairs_to_drop.add((cols[i], cols[j]))
    return pairs_to_drop

def get_top_abs_correlations(df, n=5):
    au_corr = df.corr().abs().unstack()
    labels_to_drop = get_redundant_pairs(df)
    au_corr = au_corr.drop(labels=labels_to_drop).sort_values(ascending=False)
    return au_corr[0:n]

print("Top Absolute Correlations")
print(get_top_abs_correlations(house_df, 3))
